#! /bin/bash
# Modified version by Esteban M. Navas <algodelinux@gmail.com>
# Date: 11/12/2024

RED='\033[0;31m'
GREEN='\033[0;32m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

if [ "`whoami`" != "root" ]; then
   echo -e "${RED}Please run with SUDO or root user account${NC}"
   exit 1
fi

OLDKEYFILE="/etc/apt/trusted.gpg"
KEYPATHS="/usr/share/keyrings /etc/apt/keyrings /etc/apt/trusted.gpg.d"

function HELP () {
echo -e "${WHITE}\nlaunchpad-getkeys${NC} is an utility to automatically import all Lunchpad PPAs missing GPG keys.

Usage:
   * use without any parameter to automatically import all the missing GPG keys.
   * ${WHITE}-k SERVER:PORT${NC} will pass a new keyserver, in case the default keyserver is down.
   * ${WHITE}-p PROXY:PORT${NC} lets you specify a proxy-server other than the default one.
   * ${WHITE}-r${NC} remove all expired keys.\n"
exit 0
}

function remove_expired_keys () {
if [ -f $OLDKEYFILE ]; then
   LC_ALL=C gpg --no-default-keyring --keyring=$OLDKEYFILE --list-keys | grep -E pub.*expired -A 1 > /tmp/expiredkeys

   if [ -s /tmp/expiredkeys ]; then
      for keyid in $(grep -E [[:xdigit:]]{40} /tmp/expiredkeys | sed 's/^ *//; s/ *$//; /^$/d; /^\s*$/d; s/^\t*//; s/\t*$//;'); do
          echo -e "${GREEN}Deleting KEY $keyid from $OLDKEYFILE${NC}"
          gpg --no-default-keyring --keyring=$OLDKEYFILE --batch --yes --delete-keys $keyid
      done
   fi
fi

for KEYPATH in $KEYPATHS; do
    if [ -d $KEYPATH ] && [ "$(ls -A $KEYPATH)" ]; then
       for keyfile in $(find $KEYPATH/* -not -name "*~"); do
           file $keyfile | grep -i --quiet "Encrypt"
           if [ $? -eq 0 ]; then
              LC_ALL=C gpg --no-default-keyring --keyring=$keyfile --list-keys | grep -E pub.*expired -A 1 > /tmp/expiredkeys

              if [ -s /tmp/expiredkeys ]; then
                 for keyid in $(grep -E [[:xdigit:]]{40} /tmp/expiredkeys | sed 's/^ *//; s/ *$//; /^$/d; /^\s*$/d; s/^\t*//; s/\t*$//;'); do
                     echo -e "${GREEN}Deleting KEY $keyid from $keyfile${NC}"
                     gpg --no-default-keyring --keyring=$keyfile --batch --yes --delete-keys $keyid
                 done
             fi
          fi
       done
    fi
done
}

REMOVE_EXPIRED_KEYS="no"

[ -s /etc/default/launchpad-getkeys ] && . /etc/default/launchpad-getkeys

while getopts "k:p:rh\?" opt; do
	case "$opt" in
		k ) KEYSERVER="$OPTARG"			;;
		p ) PROXY="$OPTARG"			;;
		r ) remove_expired_keys 		;;
		h ) HELP				;;
		\?) HELP				;;
		* ) warn "Unknown option '$opt'";	;;
	esac
done
shift $(($OPTIND -1))

if [[ $SERVER ]] && [[ $PORT ]]; then
   ping -c 1 $SERVER >/dev/null 2>&1

   if [ $? -eq 0 ]; then
       PROXY=http://$SERVER:$PORT
   fi
fi

if [[ $KEYSERVER ]]; then

	KEYSERVERANDPORT=$(echo $KEYSERVER | grep ":")
	if [[ ! $KEYSERVERANDPORT ]]; then
	   echo -e "${RED}Error: please enter a keyserver and a port, like so: sudo launchpad-getkeys -k SERVER:PORT${NC}"
	   exit 0
	fi
fi

if [[ $PROXY ]]; then

	PROXYSERVERANDPORT=$(echo $PROXY | grep ":")
	if [[ ! $PROXYSERVERANDPORT ]]; then
	   echo -e "${RED}Error: please enter a proxyserver and a port, like so: sudo launchpad-getkeys -p http://PROXYSERVER:PORT${NC}"
	   exit 0
	fi
fi

echo -e "${GREEN}\nPlease wait... launchpad-getkeys is running an update so
it can detect the missing GPG keys${NC}"

apt-get update -qq 2> /tmp/updateresults


MISSINGGEYS=$(cat /tmp/updateresults)

PROXY_OPTS=()
if [[ ! -z ${PROXY:-} ]]; then
    PROXY_OPTS=( --keyserver-options http-proxy=$PROXY )
fi

if [[ $MISSINGGEYS ]]; then

declare -a IMPORTED_KEYS=()

echo -e "${GREEN}\nTrying to import all the missing keys${NC}"

	IFS=$'\n'
	n=1
	while read curline; do
           echo $curline | awk '{for(i=1;i<=NF;i++) if($i=="NO_PUBKEY") print $(i+1)}' | \
           while read -r GPGKEYTOGET; do
        [ -z "${GPGKEYTOGET}" ] && continue # Skip empty values
        [[ " ${IMPORTED_KEYS[@]} " =~ " ${GPGKEYTOGET} " ]] && continue # Skip repeatable keys
        GPGTMPHOME=$(mktemp -d /tmp/gpg-tmp-home.XXXXXXXXXX)
        KEYBOX=$GPGTMPHOME/pubring.gpg
        KEYSRV_OPTS=( --keyserver hkp://keyserver.ubuntu.com:80 )
		if [[ $KEYSERVER ]]; then
            KEYSRV_OPTS=( --keyserver hkp://$KEYSERVER )
    fi

		gpg --ignore-time-conflict --no-options --no-default-keyring \
            --no-auto-check-trustdb --trust-model always \
            --homedir "$GPGTMPHOME"                      \
            --keyring "$KEYBOX"          \
            "${KEYSRV_OPTS[@]}"  "${PROXY_OPTS[@]}"                    \
            --recv $GPGKEYTOGET  2>$GPGTMPHOME/gpg.stderr
        >&2 cat $GPGTMPHOME/gpg.stderr
        TGT_NAME_BASE=$(cat  $GPGTMPHOME/gpg.stderr \
                | grep -F -m 1 "public key" \
                | sed -e 's/^[^"]*"//' \
                | sed -e 's/"[^"]*//' \
                | sed -e 's/ /__/g' \
                | sed -e 's/[<>:]//g')

        TGT_GPG_DIR=/etc/apt/trusted.gpg.d
        mkdir -p $TGT_GPG_DIR
        TGT_GPG="${TGT_GPG_DIR}/launchpad-getkeys_imported__${TGT_NAME_BASE}__${GPGKEYTOGET}.gpg"
        [ -f "$TGT_GPG" ] && rm -f "$TGT_GPG"
        gpg --ignore-time-conflict --no-options --no-default-keyring \
            --no-auto-check-trustdb --trust-model always \
            --homedir "$GPGTMPHOME" --keyring "$KEYBOX"  \
            --export  --output $TGT_GPG
        echo -e "${GREEN}Key $GPGKEYTOGET added at $TGT_GPG_DIR${NC}"
        rm -Rf $GPGTMPHOME
        IMPORTED_KEYS+=($GPGKEYTOGET)
		let n=n+1
        done
	done < /tmp/updateresults

	echo -e "${GREEN}\nlaunchpad-getkeys has finished importing all missing GPG keys.
Try running "sudo apt-get update" - you shouldn't see any key
errors anymore${NC}"
else
	echo -e "${GREEN}\nThere are no missing GPG keys!${NC}"
fi

rm /tmp/updateresults
